#ifndef OOP_SAMPLES_HEADER_H
#define OOP_SAMPLES_HEADER_H

void classAndObj();
void classMethod();
void accessModifiers();
void getterSetter();
void encapsulation();
void classConstructor();
void constructorOverload();
void destructor();
void thisPtr();
void copyConstr();
void assignOperOvrld();
void equalityOperOvrld();
void plusOperOvrld();
void incrementOvrld();
void indexOperOvrld();
void friendFunc();
void friendClassMethod();
void friendClass();
void staticKey();
void innerClass();
void agregDelegat();
void inheritance();
void inherAccessMod();
void multiInherit();
void inherAndConst();
void inherConstrChoise();
void virtualMethods();
void virtualOverride();
void abstractClass();

#endif //OOP_SAMPLES_HEADER_H
